### ISSUE TITLE
Sorum Olucak

### ISSUE THREAD

**Issue by Yavuzzhub** [Tuguberk/Savasan-Iha-Api#1]
abi merhaba öncelikle teşekkür ederiz emeğin için 
uvicorn main:app --reload bu ve diğerini nasıl çalıştırıcaz py nin kendi programındanmı

**Comment by Tuguberk** [comment]
Windows ortamında cmd'yi açarak kullanmanız gerekiyor. Python kurulurken `Add to Path` seçeneğini seçmediyseniz hata verebilir. O şekilde kaldırıp tekrar kurabilirsiniz.
